project:
  type: website

website:
  title: "communeRS"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - communities.qmd
      - resources.qmd
      - text: Contributing
        href: CONTRIBUTING.md
      - icon: github
        href: https://github.com/EllaKaye/communers
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



