project:
  type: website

website:
  title: "communeRS"
  favicon: inst/figures/communers-sticker.png
  navbar:
    right:
      - text: Home
        href: index.qmd
      - communities.qmd
      - resources.qmd
      - text: Contributing
        href: CONTRIBUTING.md
      - icon: github
        href: https://github.com/EllaKaye/communers
  
format:
  html:
    theme:
      light: [litera, styles.css]
      dark: [darkly, styles-dark.css]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    toc: true
    